# Generated by Django 3.0.7 on 2020-06-25 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ngo', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('sector', models.TextField()),
                ('category', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(default='0')),
                ('mode', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('pickup_time', models.CharField(default='none', max_length=100)),
                ('amount', models.CharField(default='0', max_length=100)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.ngodata')),
            ],
        ),
    ]
