# Generated by Django 3.0.7 on 2020-06-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', 'remove'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='belongs_to',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='can',
            options={'managed': False},
        ),
    ]
