# Generated by Django 3.0.7 on 2020-06-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_auto_20200613_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requests',
        ),
    ]
