# Generated by Django 3.0.7 on 2020-08-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20200625_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
